package net.jackadull.dirish.io

sealed trait IOResult
sealed trait IOError extends IOResult

sealed trait AddGitModuleRemoteResult extends IOResult
sealed trait CloneGitModuleResult extends IOResult
sealed trait CreateDirectoryResult extends IOResult
sealed trait GetFileInfoResult extends IOResult
sealed trait HasLocalGitChangesResult extends IOResult
sealed trait IsDirectoryEmptyEnoughAsMoveTargetResult extends IOResult
sealed trait IsDirectoryEmptyEnoughForRemovingResult extends IOResult
sealed trait ListDirectoryContentsResult extends IOResult
sealed trait MoveFileResult extends IOResult
sealed trait MoveToTrashResult extends IOResult
sealed trait RemoveGitModuleResult extends IOResult
sealed trait RemoveGitModuleRemoteResult extends IOResult

final case class GenericIOError(exception:Throwable) extends IOError with AddGitModuleRemoteResult with CloneGitModuleResult with CreateDirectoryResult with GetFileInfoResult with HasLocalGitChangesResult with IsDirectoryEmptyEnoughAsMoveTargetResult with IsDirectoryEmptyEnoughForRemovingResult with ListDirectoryContentsResult with MoveFileResult with MoveToTrashResult with RemoveGitModuleResult with RemoveGitModuleRemoteResult
object IOSuccess extends AddGitModuleRemoteResult with CloneGitModuleResult with CreateDirectoryResult with MoveFileResult with MoveToTrashResult with RemoveGitModuleRemoteResult

final case class BooleanIOResult(hasLocalChanges:Boolean) extends HasLocalGitChangesResult with IsDirectoryEmptyEnoughAsMoveTargetResult with IsDirectoryEmptyEnoughForRemovingResult
final case class DirectoryListResult(containedFiles:Set[FileInfo]) extends ListDirectoryContentsResult
final case class FileInfoResult(fileInfo:FileInfo) extends GetFileInfoResult

object GitModuleRemoteNotFound extends IOError with RemoveGitModuleRemoteResult
